name: Run Bash Script

on:
  push:
    branches:
      - main

jobs:
  run-bash-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Bash Script
        run: ./script.sh
